### ISSUE TITLE
unknown option `long'

### ISSUE THREAD

**Issue by horejsek** [schreifels/git-num#6] opened 2016-02-01 11:40 UTC
Probably it works only with some versions of Git and there is no information about which one. 

```
$ git num
error: unknown option `long'
usage: git status [options] [--] <filepattern>...
```

I am using Debian Wheezy with this Git version:

```
$ git --version
git version 1.7.10.4
```

**Comment by schreifels** [comment] 2016-02-12 03:21
I can reproduce this. It looks like that particular option is the only compatibility problem in Git 1.7.x, so I will fix this. I will also add explicit version requirements to the README for both Git and Ruby.

Thanks for the report!

**Comment by horejsek** [comment] 2016-02-12 14:39
Thanks. :-)

**Comment by schreifels** [comment] 2016-03-01 06:51
This is fixed in v2.0.1. Enjoy!

**Closed as completed by schreifels** 2016-03-01 06:51 UTC

**Comment by horejsek** [comment] 2016-03-10 15:54
Works like a charm, thank you. :-)
